spring.application.name=eduPlazas

# Conexión a la base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:eduplazasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuración de Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilitar la consola web de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#Tamaño documentos
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.jpa.properties.jakarta.persistence.validation.mode=none